CREATE DATABASE QuanLyKhachHang;
USE QuanLyKhachHang;

CREATE TABLE THAMSO (
    SoTuoiCanGiamHo INT DEFAULT 18
);
INSERT INTO THAMSO VALUES (18);

CREATE TABLE NGUOIGIAMHO (
    MaGH VARCHAR(20) PRIMARY KEY,
    TenGH VARCHAR(100),
    SDT_GH VARCHAR(15),
    Email_GH VARCHAR(100),
    GioiTinh_GH VARCHAR(10),
    NgaySinh_GH DATE,
    CCCD_GH VARCHAR(20),
    DiaChi_GH VARCHAR(200),
    QuanHe VARCHAR(50)
);

CREATE TABLE KHACHHANG (
    MaKH VARCHAR(20) PRIMARY KEY,
    TenKH VARCHAR(100),
    SDT VARCHAR(15),
    Email VARCHAR(100),
    GioiTinh VARCHAR(10),
    NgaySinh DATE,
    CCCD VARCHAR(20),
    DiaChi VARCHAR(200),
    MaGH VARCHAR(20),
    FOREIGN KEY (MaGH) REFERENCES NGUOIGIAMHO(MaGH) ON DELETE SET NULL
);